server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentmanagement
    username: root
    password: dhruvsiva061017@9
    hikari:
      maximum-pool-size: 100  
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: STUDENT-SERVICE
  
     
    